### ISSUE TITLE
Accents make fail html generation 

### ISSUE THREAD

**Issue by ThomasG77** [xdissent/jekyll-rst#5]
Using the plugin in Octopress, the word "référentiel" for example in the middle of a text isn't displayed and all the content after too.
If I use rst2html.py throught python in plugins/jekyll, it generate the right document.
I suspect the converter.rb or maybe RbST of this behaviour.
Infortunately, I'm not a Rubyist, so debugging the short converter.rb is a bit hard at the moment.

**Comment by yunglin** [comment]
The problem is in the default encoding python set. You can run `python -c "import sys;print sys.getdefaultencoding()"` to see what is the default encoding your environment. On my machine, it was using ascii which does not handle European charset nor unicode.

I add the following code to make python use utf-8 on my machine `/etc/python2.7/sitecustomize.py`
    # use utf8
    import sys
   reload(sys)
   sys.setdefaultencoding("utf-8")

**Comment by ThomasG77** [comment]
The result of the first command line is ascii
Following your advice, I'm now able to deal with that "issue". So at the end, not a ruby problem but a python config.

Thanks a lot
